language: python
python: 3.5
sudo: false
install:
 - pip wheel tox
script:
 - python setup.py develop
 - tox
deploy:
  provider: pypi
  user: ...
  password: ...
  distributions: "sdist bdist_wheel"
  on:
    - tags
notifications:
  email:
    on_success: never
    on_failure: always